const FETCH_PAGE_DATA_RESTART = 'FETCH_PAGE_DATA_RESTART'
const FETCH_PAGE_DATA_START = 'FETCH_PAGE_DATA_START'
const FETCH_PAGE_DATA_SUCCESS = 'FETCH_PAGE_DATA_SUCCESS'
const FETCH_PAGE_DATA_FAIL = 'FETCH_PAGE_DATA_FAIL'

export { FETCH_PAGE_DATA_RESTART, FETCH_PAGE_DATA_START, FETCH_PAGE_DATA_SUCCESS, FETCH_PAGE_DATA_FAIL }