const SWITCH_TAB_HOME = 'SWITCH_TAB_HOME'
const SWITCH_TAB_SORT = 'SWITCH_TAB_SORT'
const SWITCH_TAB_RELEASE_GOODS = 'SWITCH_TAB_RELEASE_GOODS'
const SWITCH_TAB_CHAT = 'SWITCH_TAB_CHAT'
const SWITCH_TAB_PERSON = 'SWITCH_TAB_PERSON'

export {
    SWITCH_TAB_HOME,
    SWITCH_TAB_SORT,
    SWITCH_TAB_RELEASE_GOODS,
    SWITCH_TAB_CHAT,
    SWITCH_TAB_PERSON
}